-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('persion_pb')


local PERSION = protobuf.Descriptor();
local PERSION_ID_FIELD = protobuf.FieldDescriptor();
local PERSION_NAME_FIELD = protobuf.FieldDescriptor();
local PERSION_EMAIL_FIELD = protobuf.FieldDescriptor();

PERSION_ID_FIELD.name = "id"
PERSION_ID_FIELD.full_name = ".persion.id"
PERSION_ID_FIELD.number = 1
PERSION_ID_FIELD.index = 0
PERSION_ID_FIELD.label = 2
PERSION_ID_FIELD.has_default_value = false
PERSION_ID_FIELD.default_value = 0
PERSION_ID_FIELD.type = 3
PERSION_ID_FIELD.cpp_type = 2

PERSION_NAME_FIELD.name = "name"
PERSION_NAME_FIELD.full_name = ".persion.name"
PERSION_NAME_FIELD.number = 2
PERSION_NAME_FIELD.index = 1
PERSION_NAME_FIELD.label = 2
PERSION_NAME_FIELD.has_default_value = false
PERSION_NAME_FIELD.default_value = ""
PERSION_NAME_FIELD.type = 9
PERSION_NAME_FIELD.cpp_type = 9

PERSION_EMAIL_FIELD.name = "email"
PERSION_EMAIL_FIELD.full_name = ".persion.email"
PERSION_EMAIL_FIELD.number = 3
PERSION_EMAIL_FIELD.index = 2
PERSION_EMAIL_FIELD.label = 1
PERSION_EMAIL_FIELD.has_default_value = false
PERSION_EMAIL_FIELD.default_value = ""
PERSION_EMAIL_FIELD.type = 9
PERSION_EMAIL_FIELD.cpp_type = 9

PERSION.name = "persion"
PERSION.full_name = ".persion"
PERSION.nested_types = {}
PERSION.enum_types = {}
PERSION.fields = {PERSION_ID_FIELD, PERSION_NAME_FIELD, PERSION_EMAIL_FIELD}
PERSION.is_extendable = false
PERSION.extensions = {}

persion = protobuf.Message(PERSION)

